config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :animations, only: [:index, :show,] do
    resources :favorites, only: [:create, :destroy]
    resources :reviews, only: [:index, :new, :create]
    collection do
      get 'search_results'
    end
  end
end

app/models/animation.rb
class Animation < ApplicationRecord
  enum season: { spring: 1, summer: 2, autumn: 3, winter: 4 }
  has_one :animation_detail
  # belongs_to :user
  # has_many :favorites, dependent: :destroy
  # has_many :reviews, dependent: :destroy

  # Annictから情報を取得
  def import_from_annict
    base_url = "https://api.annict.com/v1"
    access_token = ENV["ANNICT_ACCESS_TOKEN"]

    start_year = 1970 # どの年からデータを取得したいかを指定
    end_year = Date.today.year
    seasons = ["spring", "summer", "autumn", "winter"]

    (start_year..end_year).each do |year|
      seasons.each.with_index(1) do |season, index|
        # 初回リクエストはデータの総数を調べるために実行
        data = JSON.parse(Faraday.get("#{base_url}/works?fields=id&per_page=50&filter_season=#{year}-#{season}&sort_watchers_count=desc&access_token=#{access_token}").body)

        data_count = data["total_count"]         # データの数
        page_count = (data_count / 50.to_f).ceil # ページの数

        current_page = 1

        # 現在のページ <= ページの数になるまで繰り返し処理を実行
        while current_page <= page_count do
          data = JSON.parse(Faraday.get("#{base_url}/works?fields=title,images,twitter_username,official_site_url,media_text,syobocal_tid,season_name_text&page=#{current_page}&per_page=50&filter_season=#{year}-#{season}&sort_watchers_count=desc&access_token=#{access_token}").body)
          animations = data["works"]

          animations.each do |animation|
            # すでにレコードが存在する場合は更新、無ければ新規作成
            Animation.find_or_initialize_by(title: animation["title"]).update(
              year: year,
              season: index,
              image: animation["images"]["facebook"]["og_image_url"],
              twitter_username: animation["twitter_username"],
              official_site_url: animation["official_site_url"],
              media_text: animation["media_text"],
              syobocal_tid: animation["syobocal_tid"],
              season_name_text: animation["season_name_text"]
            )
          end

          current_page += 1
        end
      end
    end
  end

  # def favorited?(user)
  #   favorites.where(user_id: user.id).exists?
  # end

  def self.ransackable_attributes(auth_object = nil)
    %w[title]
  end

  # def avg_score
  #   unless self.reviews.empty?
  #     reviews.average(:score).round(1).to_f
  #   else
  #     0.0
  #   end
  # end

  # def reviews_score_percentage
  #   unless self.reviews.empty?
  #     reviews.average(:score).round(1).to_f*100/5
  #   else
  #     0.0
  #   end
  # end
end

app/models/animation_detail.rb
class AnimationDetail < ApplicationRecord
  serialize :staffs, Array
  serialize :casts, Array

  belongs_to :animation

  # しょぼいカレンダーから情報を取得
  def import_from_syobocal
    titles = Syobocal::DB::TitleLookup.get({ "TID" => "*" })

    titles.each do |title|
      comment = title[:comment]
      parser = Syobocal::Comment::Parser.new(comment)

      # 製作陣
      staffs = parser.staffs.map do |staff|
        {
          "role": staff.instance_variable_get("@role"),
          "name": staff.instance_variable_get("@people")[0].instance_variable_get("@name")
        }
      end

      # キャスト陣
      casts = parser.casts.map do |cast|
        {
          "character": cast.instance_variable_get("@character"),
          "name": cast.instance_variable_get("@people")[0].instance_variable_get("@name")
        }
      end

      tid = title[:tid]
      animation = Animation.find_by(syobocal_tid: tid)

      # すでにレコードが存在する場合は更新、無ければ新規作成
      AnimationDetail.find_or_initialize_by(syobocal_tid: tid).update(
        animation_id: animation ? animation.id : nil,
        staffs: staffs,
        casts: casts
      )
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/animations_controller.rb
class AnimationsController < ApplicationController

  def index
    @animations = Animation.all.order(created_at: :desc).page(params[:page]).per(16)
  end

  def show
    @animation = Animation.find_by(id: params[:id])
    @animations = Animation.where(id: params[:id])
    @animations_detail = AnimationDetail.where(animation_id: params[:id])
    # @review = @animation.reviews.order(id: :desc)
  end

  def search_results
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search

  def set_search
    @q = Animation.ransack(params[:q])
    @animations = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(16)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    today = Date.today

    if [1, 2, 3].include?(today.mon)
      today_season = 4
    elsif [4, 5, 6].include?(today.mon)
      today_season = 1
    elsif [7, 8, 9].include?(today.mon)
      today_season = 2
    elsif [10, 11, 12].include?(today.mon)
      today_season = 3
    end

    @animations = Animation.where(season: today_season, year: today.year)
  end
end

app/helpers/animations_helper.rb
module AnimationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/animations/index.html.erb
<div class="py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <!-- text - start -->
    <div class="mb-10 md:mb-16">
      <h2 class="primary-content text-2xl lg:text-3xl font-bold mb-4 md:mb-6 pl-4">アニメ一覧</h2>
    </div>
    <!-- text - end -->

    <div class="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      <% @animations.each do |animation| %>
        <!-- product - start -->
        <div>
          <%= link_to image_tag(animation.image, class: "w-full h-full object-cover object-center group-hover:scale-110 transition duration-200", alt: animation.title), "/animations/#{animation.id}", class: "group h-36 block bg-gray-100 rounded-t-lg overflow-hidden relative" %>
          <div class="flex justify-between items-start bg-base-200 rounded-b-lg gap-2 p-4">
            <div class="flex flex-col truncate">
              <div class="flex">
                <div class="relative">
                  <div class="text-gray-500 text-xl">★★★★★</div>
                </div>
              </div>
              <%= link_to animation.title, "/animations/#{animation.id}", class: "secondary-content hover:base-content lg:text-lg font-semibold transition duration-100 mt-1 truncate" %>
            </div>
          </div>
        </div>
        <% end %>
        <!-- product - end -->
    </div>
  </div>
</div>

<%= paginate @animations %>

app/views/animations/search_results.html.erb
<div class="mb-10 md:mb-16">
  <% if @q.title_cont != nil %>
    <h2 class="text-primary-content text-2xl lg:text-3xl font-bold mb-4 md:mb-6 pl-4"><%= "#{@q.title_cont} の検索結果" %></h2>
  <% else %>
    <h2 class="text-primary-content text-2xl lg:text-3xl font-bold mb-4 md:mb-6 pl-4"><%= "一致するアニメがありません。" %></h2>
  <% end %>
</div>
<div class="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      <% @animations.each do |animation| %>
        <!-- product - start -->
        <div>
          <%= link_to image_tag(animation.image, class: "w-full h-full object-cover object-center group-hover:scale-110 transition duration-200", alt: animation.title), "/animations/#{animation.id}", class: "group h-36 block bg-gray-100 rounded-t-lg overflow-hidden relative" %>
          <div class="flex justify-between items-start bg-base-200 rounded-b-lg gap-2 p-4">
            <div class="flex flex-col truncate">
              <div class="flex">
                <div class="relative">
                  <div class="text-gray-500 text-xl">★★★★★</div>
                </div>
              </div>
              <%= link_to animation.title, "/animations/#{animation.id}", class: "secondary-content hover:base-content lg:text-lg font-semibold transition duration-100 mt-1 truncate" %>
            </div>
          </div>
        </div>
        <% end %>
        <!-- product - end -->
    </div>
  </div>
</div>

<%= paginate @animations %>

app/views/animations/show.html.erb
<div class="text-gray-600 body-font overflow-hidden">
  <% @animations.each do |animation| %>
  <% @animations_detail.each do |animationD| %>
    <div class="container px-5 py-12 mx-auto">
      <div class="mx-auto flex flex-wrap">
        <div class="lg:w-2/5 w-full h-full">
            <%= image_tag animation.image, alt: animation.title, class: "object-cover object-center rounded" %>
          <div class="flex justify-end align-center mt-2">
            <%= button_to new_animation_review_path(@animation.id), method: :get do %>
              <div class="flex px-6">
                <i class="fa-regular fa-comment fa-2x"></i>
                <p class="text-2xl ml-1">
                </p>
                </div>
            <% end %>
          </div>
        </div>
        <div class="lg:w-3/5 w-full lg:pl-10 lg:py-2 mt-6 lg:mt-0">
          <h1 class="text-gray-300 text-3xl title-font font-medium mb-1"><%= animation.title %></h1>
          <div class="flex">
            <div class="relative">
              <div class="text-gray-500 text-xl">★★★★★</div>
            </div>
          </div>
          <p class="text-gray-400 leading-relaxed py-2"><%= animation.season_name_text%> | <%= animation.media_text %></p>
          <%= link_to '公式サイト', animation.official_site_url, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline py-2" %>
          <%= link_to 'Twitter', "https://twitter.com/#{animation.twitter_username}", class: "font-medium text-blue-600 dark:text-blue-500 hover:underline py-2" %>
          <p class="text-gray-400 leading-relaxed pt-4 pb-2 font-black">スタッフ</p>
          <% animationD.staffs.each do |staff| %>
          <span class="text-sm font-normal inline-block py-1 px-2 uppercase rounded text-gray-400 bg-gray-700 uppercase last:mr-0 mr-1"><%= staff[:role] %> : <%= staff[:name] %></span>
          <% end %>
          <p class="text-gray-400 leading-relaxed pt-4 pb-2 font-black">キャスト</p>
          <% animationD.casts.each do |cast| %>
          <span class="text-sm font-normal inline-block py-1 px-2 uppercase rounded text-gray-400 bg-gray-700 uppercase last:mr-0 mr-1"><%= cast[:name] %>(<%= cast[:character] %>)</span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/homes/index.html.erb
<h2>今期放送中のアニメ</h2>
<div class="carousel carousel-center rounded-box">
  <% @animations.each do |animation| %>
    <div class="mx-2">
      <%= link_to image_tag(animation.image, class: "w-full h-full object-cover object-center group-hover:scale-110 transition duration-200", alt: animation.title), "/animations/#{animation.id}", class: "group h-36 block bg-gray-100 rounded-t-lg overflow-hidden relative" %>
      <div class="flex justify-between items-start bg-base-200 rounded-b-lg gap-2 p-4">
        <div class="flex flex-col truncate">
          <div class="flex">
            <div class="relative">
              <div class="text-gray-500 text-xl">★★★★★</div>
            </div>
          </div>
          <%= link_to animation.title, "/animations/#{animation.id}", class: "w-60 secondary-content hover:base-content lg:text-lg font-semibold transition duration-100 mt-1 truncate" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer footer-center p-4 bg-base-300 text-base-content">
  <div>
    <p>Copyright © 2023 - All right reserved by ACME Industries Ltd</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to 'Anikomi', root_path, class: "btn btn-ghost normal-case text-xl"  %>
  </div>
  <div class="flex-none gap-2">
    <div class="form-control">
      <%= search_form_for @q, url: search_results_animations_path do |f| %>
        <form>   
          <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
          <div class="relative">
            <%= f.search_field :title_cont, class: "input input-bordered", placeholder: "タイトルで検索", value: "" %>
          </div>
        </form>
      <% end %>
    </div>
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <img src="/images/stock/photo-1534528741775-53994a69daeb.jpg" />
        </div>
      </label>
      <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
        <li>
          <a class="justify-between">
            Profile
            <span class="badge">New</span>
          </a>
        </li>
        <li><a>Settings</a></li>
        <li><a>Logout</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="dark">
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>